CREATE TABLE `post` (
  `id` int NOT NULL AUTO_INCREMENT,
  `app_id` int NOT NULL,
  `creator_id` int NOT NULL,
  `collection_id` int DEFAULT NULL,
  `email_campaign_id` int DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `body` text DEFAULT NULL,
  `styled_html` text DEFAULT NULL,
  `style` text,
  `status` char(4) NOT NULL DEFAULT 'DFLT',
  `active` boolean DEFAULT TRUE,
  `hidden` boolean DEFAULT FALSE,
  `image_uri` varchar(255) DEFAULT NULL,
  `token_royalty` int DEFAULT 1000,
  `token_supply` int DEFAULT 0,
  `token_supply_cap` int DEFAULT NULL,
  `token_price` int DEFAULT NULL,
  `token_prefix` varchar(1024) DEFAULT '',
  `token_uri` varchar(255) DEFAULT NULL,
  `token_animation_url` varchar(255) DEFAULT NULL,
  `token_signature` varchar(132) DEFAULT NULL,
  `asset_uri` varchar(500) DEFAULT NULL,
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `no_duplicate_assets` (`asset_uri`),
  KEY `app_id` (`app_id`),
  KEY `creator_id` (`creator_id`),
  KEY `collection_id` (`collection_id`),
  KEY `email_campaign_id` (`email_campaign_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
